export default [{
  id: '5',
  "image": "https://notjustdev-dummy.s3.us-east-2.amazonaws.com/images/products/cleanarchitecture.jpg",
  "images":["https://i.ebayimg.com/images/g/sY8AAOSw9~RXJA-f/s-l1600.jpg", "https://m.media-amazon.com/images/I/51x2uufH6SL.jpg", "https://m.media-amazon.com/images/I/51x2uufH6SL.jpg"],
  "brand": "PS3",
  "price": 250,
  "rating": 1,
  "numReviews": 0,
  "isFeatured": true,
  "name": "Fantom Pratik Elektrikli Süpürge",
  "description": "2011 Fiat Linea ACTIVE PLUS 1.3 MULTIJET 90 HP W/O MP3",
  "category": 1,
  "countInStock": 25,
},{
  id: '6',
  "image": "https://notjustdev-dummy.s3.us-east-2.amazonaws.com/images/products/cleancode.jpg",
  "images":["https://i.ebayimg.com/images/g/sY8AAOSw9~RXJA-f/s-l1600.jpg", "https://m.media-amazon.com/images/I/51x2uufH6SL.jpg", "https://m.media-amazon.com/images/I/51x2uufH6SL.jpg"],
  "brand": "IKEA",
  "price": 350.9,
  "rating": 5,
  "numReviews": 0,
  "isFeatured": true,
  "name": "Fantom Pratik Elektrikli Süpürge",
  "description": "2011 Fiat Linea ACTIVE PLUS 1.3 MULTIJET 90 HP W/O MP3",
  "category": 2,
  "countInStock": 10,
},{
  id: '7',
  "image": "https://notjustdev-dummy.s3.us-east-2.amazonaws.com/images/products/imac1.jpg",
  "images":["https://i.ebayimg.com/images/g/sY8AAOSw9~RXJA-f/s-l1600.jpg", "https://m.media-amazon.com/images/I/51x2uufH6SL.jpg", "https://m.media-amazon.com/images/I/51x2uufH6SL.jpg"],

  "brand": "OBI",
  "price": 1350.9,
  "rating": 5,
  "numReviews": 0,
  "isFeatured": true,
  "name": "Fantom Pratik Elektrikli Süpürge",
  "description": "2011 Fiat Linea ACTIVE PLUS 1.3 MULTIJET 90 HP W/O MP3",
  "category": 3,
  "countInStock": 10,
},{
  id: '8',
  "image": "https://notjustdev-dummy.s3.us-east-2.amazonaws.com/images/products/keyboard1.jpg",
  "images":["https://i.ebayimg.com/images/g/sY8AAOSw9~RXJA-f/s-l1600.jpg", "https://m.media-amazon.com/images/I/51x2uufH6SL.jpg", "https://m.media-amazon.com/images/I/51x2uufH6SL.jpg"],

  "brand": "OBI",
  "price": 490.9,
  "rating": 5,
  "numReviews": 0,
  "isFeatured": true,
  "name": "Fantom Pratik Elektrikli Süpürge",
  "description": "2011 Fiat Linea ACTIVE PLUS 1.3 MULTIJET 90 HP W/O MP3",
  "category": 4,
  "countInStock": 5,
},{
  id: '9',
  "image": "https://notjustdev-dummy.s3.us-east-2.amazonaws.com/images/products/keyboard2.jpg",
  "images":["https://i.ebayimg.com/images/g/sY8AAOSw9~RXJA-f/s-l1600.jpg", "https://m.media-amazon.com/images/I/51x2uufH6SL.jpg", "https://m.media-amazon.com/images/I/51x2uufH6SL.jpg"],
  "brand": "Mobilix",
  "price": 1000,
  "rating": 5,
  "numReviews": 0,
  "isFeatured": true,
  "name": "Fantom Pratik Elektrikli Süpürge",
  "description": "2011 Fiat Linea ACTIVE PLUS 1.3 MULTIJET 90 HP W/O MP3",
  "category": 2,
  "countInStock": 2,
},{
  id: '10',
  "image": "https://notjustdev-dummy.s3.us-east-2.amazonaws.com/images/products/mouse1.jpg",
  "images":["https://i.ebayimg.com/images/g/sY8AAOSw9~RXJA-f/s-l1600.jpg", "https://m.media-amazon.com/images/I/51x2uufH6SL.jpg", "https://m.media-amazon.com/images/I/51x2uufH6SL.jpg"],
  "brand": "Mobilix",
  "price": 1000,
  "rating": 5,
  "numReviews": 0,
  "isFeatured": true,
  "name": "Sofa",
  "description": "2011 Fiat Linea ACTIVE PLUS 1.3 MULTIJET 90 HP W/O MP3",
  "category": 3,
  "countInStock": 2,
}]